<?php

function prd_country_lookup($key) {
	$countries = prd_country_array();
	return $countries[$key];
}

function prd_state_lookup($key) {
	$states = prd_state_array();
	return $states[$key];
}


function prd_state_array() {
	$states = array(
		'AL'=>'Alabama',
		'AK'=>'Alaska',
		'AZ'=>'Arizona',
		'AR'=>'Arkansas',
		'CA'=>'California',
		'CO'=>'Colorado',
		'CT'=>'Connecticut',
		'DE'=>'Delaware',
		'DC'=>'District of Columbia',
		'FL'=>'Florida',
		'GA'=>'Georgia',
		'HI'=>'Hawaii',
		'ID'=>'Idaho',
		'IL'=>'Illinois',
		'IN'=>'Indiana',
		'IA'=>'Iowa',
		'KS'=>'Kansas',
		'KY'=>'Kentucky',
		'LA'=>'Louisiana',
		'ME'=>'Maine',
		'MD'=>'Maryland',
		'MA'=>'Massachusetts',
		'MI'=>'Michigan',
		'MN'=>'Minnesota',
		'MS'=>'Mississippi',
		'MO'=>'Missouri',
		'MT'=>'Montana',
		'NE'=>'Nebraska',
		'NV'=>'Nevada',
		'NH'=>'New Hampshire',
		'NJ'=>'New Jersey',
		'NM'=>'New Mexico',
		'NY'=>'New York',
		'NC'=>'North Carolina',
		'ND'=>'North Dakota',
		'OH'=>'Ohio',
		'OK'=>'Oklahoma',
		'OR'=>'Oregon',
		'PA'=>'Pennsylvania',
		'RI'=>'Rhode Island',
		'SC'=>'South Carolina',
		'SD'=>'South Dakota',
		'TN'=>'Tennessee',
		'TX'=>'Texas',
		'UT'=>'Utah',
		'VT'=>'Vermont',
		'VA'=>'Virginia',
		'WA'=>'Washington',
		'WV'=>'West Virginia',
		'WI'=>'Wisconsin',
		'WY'=>'Wyoming',
		'AB'=>'Alberta',
		'BC'=>'British Columbia',
		'MB'=>'Manitoba',
		'NB'=>'New Brunswick',
		'NL'=>'Newfoundland and Labrador',
		'NS'=>'Nova Scotia',
		'NT'=>'Northwest Territories',
		'NU'=>'Nunavut',
		'ON'=>'Ontario',
		'PE'=>'Prince Edward Island',
		'QC'=>'Quebec',
		'SK'=>'Saskatchewan',
		'YT'=>'Yukon',
	);
	return $states;
}

function prd_country_array() {
	$countries = array (
		'US' => 'UNITED STATES',
		'CA' => 'CANADA',
		'AD' => 'ANDORRA',
		'AE' => 'UNITED ARAB EMIRATES',
		'AF' => 'AFGHANISTAN',
		'AG' => 'ANTIGUA AND BARBUDA',
		'AG' => 'ANTIGUA & BARB.',
		'AI' => 'ANGUILLA',
		'AL' => 'ALBANIA',
		'AM' => 'ARMENIA',
		'AN' => 'NETHERLANDS ANTILLES',
		'AN' => 'NETH. ANTILLES',
		'AO' => 'ANGOLA',
		'AQ' => 'ANTARCTICA',
		'AR' => 'ARGENTINA',
		'AS' => 'AMERICAN SAMOA',
		'AT' => 'AUSTRIA',
		'AU' => 'AUSTRALIA',
		'AW' => 'ARUBA',
		'AX' => 'ALAND ISLANDS',
		'AZ' => 'AZERBAIJAN',
		'BA' => 'BOSNIA AND HERZEGOVINA',
		'BA' => 'HERZEGOVINA',
		'BB' => 'BARBADOS',
		'BD' => 'BANGLADESH',
		'BE' => 'BELGIUM',
		'BF' => 'BURKINA FASO',
		'BG' => 'BULGARIA',
		'BH' => 'BAHRAIN',
		'BI' => 'BURUNDI',
		'BJ' => 'BENIN',
		'BL' => 'SAINT BARTHELEMY',
		'BM' => 'BERMUDA',
		'BN' => 'BRUNEI',
		'BO' => 'BOLIVIA',
		'BQ' => 'BONAIRE, SAINT EUSTATIUS AND',
		'BR' => 'BRAZIL',
		'BS' => 'BAHAMAS',
		'BT' => 'BHUTAN',
		'BV' => 'BOUVET ISLAND',
		'BW' => 'BOTSWANA',
		'BY' => 'BELARUS',
		'BZ' => 'BELIZE',
		'CA' => 'CANADA',
		'CC' => 'COCOS (KEELING) ISLANDS',
		'CD' => 'CONGO, THE DEMOCRATIC REPUBLIC',
		'CF' => 'CENTRAL AFRICAN REPUBLIC',
		'CF' => 'CENTRAL AFRICAN',
		'CG' => 'CONGO',
		'CH' => 'SWITZERLAND',
		'CI' => 'COTE D`IVOIRE',
		'CK' => 'COOK ISLANDS',
		'CL' => 'CHILE',
		'CM' => 'CAMEROON',
		'CN' => 'CHINA',
		'CO' => 'COLOMBIA',
		'CR' => 'COSTA RICA',
		'CS' => 'SERBIA AND MONTENEGRO',
		'CU' => 'CUBA',
		'CV' => 'CAPE VERDE',
		'CW' => 'CURACAO',
		'CX' => 'CHRISTMAS ISLAND',
		'CY' => 'CYPRUS',
		'CZ' => 'CZECH REPUBLIC',
		'DE' => 'GERMANY',
		'DJ' => 'DJIBOUTI',
		'DK' => 'DENMARK',
		'DM' => 'DOMINICA',
		'DO' => 'DOMINICAN REPUBLIC',
		'DO' => 'DOMINICAN REPUB',
		'DZ' => 'ALGERIA',
		'EC' => 'ECUADOR',
		'EE' => 'ESTONIA',
		'EG' => 'EGYPT',
		'EH' => 'WESTERN SAHARA',
		'ER' => 'ERITREA',
		'ES' => 'SPAIN',
		'ET' => 'ETHIOPIA',
		'FI' => 'FINLAND',
		'FJ' => 'FIJI',
		'FK' => 'FALKLAND ISLANDS',
		'FK' => 'FALKLAND ISLAND',
		'FM' => 'MICRONESIA, FEDERATED STATES O',
		'FO' => 'FAROE ISLANDS',
		'FR' => 'FRANCE',
		'GA' => 'GABON',
		'GB' => 'UNITED KINGDOM',
		'GB' => 'ENGLAND',
		'GB' => 'GREAT BRITAIN',
		'GB' => 'NORTHERN IRELAND',
		'GB' => 'SCOTLAND',
		'GB' => 'UK',
		'GB' => 'WALES',
		'GD' => 'GRENADA',
		'GE' => 'GEORGIA',
		'GE' => 'REPUBLIC OF GEORGIA',
		'GE' => 'GEORGIAREPUBLIC',
		'GF' => 'FRENCH GUIANA',
		'GG' => 'GUERNSEY',
		'GH' => 'GHANA',
		'GI' => 'GIBRALTAR',
		'GL' => 'GREENLAND',
		'GM' => 'GAMBIA',
		'GN' => 'GUINEA',
		'GP' => 'GUADELOUPE',
		'GQ' => 'EQUATORIAL GUINEA',
		'GR' => 'GREECE',
		'GS' => 'SOUTH GEORGIA AND THE SOUTH SA',
		'GS' => 'SOUTH GEORGIA',
		'GT' => 'GUATEMALA',
		'GW' => 'GUINEA-BISSAU',
		'GW' => 'GUINEA BISSAU',
		'GY' => 'GUYANA',
		'HK' => 'HONG KONG',
		'HM' => 'HEARD ISLAND AND MCDONALD ISLA',
		'HN' => 'HONDURAS',
		'HR' => 'CROATIA',
		'HT' => 'HAITI',
		'HU' => 'HUNGARY',
		'IB' => 'ISLE OF MAN',
		'ID' => 'INDONESIA',
		'IE' => 'IRELAND',
		'IL' => 'ISRAEL',
		'IN' => 'INDIA',
		'IO' => 'BRITISH INDIAN OCEAN TERRITORY',
		'IQ' => 'IRAQ',
		'IR' => 'IRAN',
		'IS' => 'ICELAND',
		'IT' => 'ITALY',
		'JE' => 'JERSEY',
		'JM' => 'JAMAICA',
		'JO' => 'JORDAN',
		'JP' => 'JAPAN',
		'KE' => 'KENYA',
		'KG' => 'KYRGYZSTAN',
		'KH' => 'CAMBODIA',
		'KI' => 'KIRIBATI',
		'KM' => 'COMOROS',
		'KN' => 'SAINT KITTS AND NEVIS',
		'KP' => 'NORTH KOREA',
		'KR' => 'SOUTH KOREA',
		'KW' => 'KUWAIT',
		'KY' => 'CAYMAN ISLANDS',
		'KZ' => 'KAZAKHSTAN',
		'LA' => 'LAOS PEOPLES DEMOCRATIC REPUBL',
		'LA' => 'LAOS',
		'LB' => 'LEBANON',
		'LC' => 'SAINT LUCIA',
		'LI' => 'LIECHTENSTEIN',
		'LK' => 'SRI LANKA',
		'LR' => 'LIBERIA',
		'LS' => 'LESOTHO',
		'LT' => 'LITHUANIA',
		'LU' => 'LUXEMBOURG',
		'LV' => 'LATVIA',
		'LY' => 'LIBYAN ARAB JAMAHIRIYA',
		'MA' => 'MOROCCO',
		'MC' => 'MONACO',
		'MD' => 'MOLDOVA, REPUBLIC OF',
		'MD' => 'MOLDOVA',
		'ME' => 'MONTENEGRO',
		'MF' => 'SAINT MARTIN',
		'MG' => 'MADAGASCAR',
		'MH' => 'MARSHALL ISLANDS',
		'MK' => 'MACEDONIA',
		'ML' => 'MALI',
		'MM' => 'MYANMAR',
		'MN' => 'MONGOLIA',
		'MO' => 'MACAU',
		'MP' => 'NORTHERN MARIANA ISLANDS',
		'MQ' => 'MARTINIQUE',
		'MR' => 'MAURITANIA',
		'MS' => 'MONTSERRAT',
		'MT' => 'MALTA',
		'MU' => 'MAURITIUS',
		'MV' => 'MALDIVES',
		'MW' => 'MALAWI',
		'MX' => 'MEXICO',
		'MY' => 'MALAYSIA',
		'MZ' => 'MOZAMBIQUE',
		'NA' => 'NAMIBIA',
		'NC' => 'NEW CALEDONIA',
		'NE' => 'NIGER',
		'NF' => 'NORFOLK ISLAND',
		'NG' => 'NIGERIA',
		'NI' => 'NICARAGUA',
		'NL' => 'NETHERLANDS',
		'NL' => 'THE NETHERLANDS',
		'NO' => 'NORWAY',
		'NP' => 'NEPAL',
		'NR' => 'NAURU',
		'NU' => 'NIUE',
		'NZ' => 'NEW ZEALAND',
		'OM' => 'OMAN',
		'PA' => 'PANAMA',
		'PE' => 'PERU',
		'PF' => 'FRENCH POLYNESIA',
		'PF' => 'FR. POLYNESIA',
		'PG' => 'PAPUA NEW GUINEA',
		'PG' => 'PAPUA N. GUINEA',
		'PH' => 'PHILIPPINES',
		'PK' => 'PAKISTAN',
		'PL' => 'POLAND',
		'PM' => 'SAINT PIERRE AND MIQUELON',
		'PN' => 'PITCAIRN',
		'PS' => 'PALESTINIAN TERRITORY',
		'PT' => 'PORTUGAL',
		'PW' => 'PALAU',
		'PY' => 'PARAGUAY',
		'QA' => 'QATAR',
		'RE' => 'RÉUNION',
		'RE' => 'REUNION',
		'RO' => 'ROMANIA',
		'RS' => 'SERBIA',
		'RS' => 'KOSOVO',
		'RU' => 'RUSSIAN FEDERATION',
		'RU' => 'RUSSIA',
		'RW' => 'RWANDA',
		'SA' => 'SAUDI ARABIA',
		'SB' => 'SOLOMON ISLANDS',
		'SC' => 'SEYCHELLES',
		'SD' => 'SUDAN',
		'SE' => 'SWEDEN',
		'SG' => 'REPUBLIC OF SINGAPORE',
		'SG' => 'SINGAPORE',
		'SH' => 'SAINT HELENA',
		'SI' => 'SLOVENIA',
		'SJ' => 'SVALBARD AND JAN MAYEN ISLANDS',
		'SK' => 'SLOVAKIA',
		'SK' => 'SLOVAK REPUBLIC',
		'SL' => 'SIERRA LEONE',
		'SM' => 'SAN MARINO',
		'SN' => 'SENEGAL',
		'SO' => 'SOMALIA',
		'SR' => 'SURINAME',
		'ST' => 'SAO TOME AND PRINCIPE',
		'SV' => 'EL SALVADOR',
		'SX' => 'SINT MAARTEN (DUTCH PART)',
		'SY' => 'SYRIAN ARAB REPUBLIC',
		'SY' => 'SYRIA',
		'SZ' => 'SWAZILAND',
		'TC' => 'TURKS AND CAICOS ISLANDS',
		'TD' => 'CHAD',
		'TF' => 'FRENCH SOUTHERN TERRITORIES',
		'TG' => 'TOGO',
		'TH' => 'THAILAND',
		'TJ' => 'TAJIKISTAN',
		'TK' => 'TOKELAU',
		'TL' => 'TIMOR-LESTE',
		'TM' => 'TURKMENISTAN',
		'TN' => 'TUNISIA',
		'TO' => 'TONGA',
		'TR' => 'TURKEY',
		'TT' => 'TRINIDAD AND TOBAGO',
		'TT' => 'TRINIDAD',
		'TV' => 'TUVALU',
		'TW' => 'TAIWAN',
		'TW' => 'TAIWAN, PROVINCE OF CHINA',
		'TZ' => 'TANZANIA',
		'UA' => 'UKRAINE',
		'UG' => 'UGANDA',
		'US' => 'UNITED STATES',
		'UY' => 'URUGUAY',
		'UZ' => 'UZBEKISTAN',
		'VA' => 'HOLY SEE (VATICAN CITY STATE)',
		'VA' => 'HOLY SEE',
		'VC' => 'SAINT VINCENT AND THE GRENADIN',
		'VC' => 'ST VINCENT',
		'VE' => 'VENEZUELA',
		'VG' => 'VIRGIN ISLANDS (BRITISH)',
		'VG' => 'VIRGIN ISLANDS',
		'VN' => 'VIETNAM',
		'VU' => 'VANUATU',
		'WF' => 'WALLIS AND FUTUNA',
		'WN' => 'WEST INDIES',
		'WS' => 'SAMOA (INDEPENDENT)',
		'YE' => 'YEMEN',
		'YT' => 'MAYOTTE',
		'ZA' => 'SOUTH AFRICA',
		'ZM' => 'ZAMBIA',
		'ZW' => 'ZIMBABWE',
	);
	return $countries;
}

function prd_country_array_for_terminal() {
	$countries = array (
		'AFGHANISTAN',
		'ALAND ISLANDS',
		'ALBANIA',
		'ALGERIA',
		'AMERICAN SAMOA',
		'ANDORRA',
		'ANGOLA',
		'ANGUILLA',
		'ANTARCTICA',
		'ANTIGUA & BARB.',
		'ANTIGUA AND BARBUDA',
		'ARGENTINA',
		'ARMENIA',
		'ARUBA',
		'AUSTRALIA',
		'AUSTRIA',
		'AZERBAIJAN',
		'BAHAMAS',
		'BAHRAIN',
		'BANGLADESH',
		'BARBADOS',
		'BELARUS',
		'BELGIUM',
		'BELIZE',
		'BENIN',
		'BERMUDA',
		'BHUTAN',
		'BOLIVIA',
		'BONAIRE, SAINT EUSTATIUS AND',
		'BOSNIA AND HERZEGOVINA',
		'BOTSWANA',
		'BOUVET ISLAND',
		'BRAZIL',
		'BRITISH INDIAN OCEAN TERRITORY',
		'BRUNEI',
		'BULGARIA',
		'BURKINA FASO',
		'BURUNDI',
		'CAMBODIA',
		'CAMEROON',
		'CAPE VERDE',
		'CAYMAN ISLANDS',
		'CENTRAL AFRICAN REPUBLIC',
		'CENTRAL AFRICAN',
		'CHAD',
		'CHILE',
		'CHINA',
		'CHRISTMAS ISLAND',
		'COCOS (KEELING) ISLANDS',
		'COLOMBIA',
		'COMOROS',
		'CONGO',
		'CONGO, THE DEMOCRATIC REPUBLIC',
		'COOK ISLANDS',
		'COSTA RICA',
		'COTE D`IVOIRE',
		'CROATIA',
		'CUBA',
		'CURACAO',
		'CYPRUS',
		'CZECH REPUBLIC',
		'DENMARK',
		'DJIBOUTI',
		'DOMINICA',
		'DOMINICAN REPUB',
		'DOMINICAN REPUBLIC',
		'ECUADOR',
		'EGYPT',
		'EL SALVADOR',
		'ENGLAND',
		'EQUATORIAL GUINEA',
		'ERITREA',
		'ESTONIA',
		'ETHIOPIA',
		'FALKLAND ISLAND',
		'FALKLAND ISLANDS',
		'FAROE ISLANDS',
		'FIJI',
		'FINLAND',
		'FR. POLYNESIA',
		'FRANCE',
		'FRENCH GUIANA',
		'FRENCH POLYNESIA',
		'FRENCH SOUTHERN TERRITORIES',
		'GABON',
		'GAMBIA',
		'GEORGIA',
		'GEORGIAREPUBLIC',
		'GERMANY',
		'GHANA',
		'GIBRALTAR',
		'GREAT BRITAIN',
		'GREECE',
		'GREENLAND',
		'GRENADA',
		'GUADELOUPE',
		'GUATEMALA',
		'GUERNSEY',
		'GUINEA BISSAU',
		'GUINEA',
		'GUINEA-BISSAU',
		'GUYANA',
		'HAITI',
		'HEARD ISLAND AND MCDONALD ISLA',
		'HERZEGOVINA',
		'HOLY SEE (VATICAN CITY STATE)',
		'HOLY SEE',
		'HONDURAS',
		'HONG KONG',
		'HUNGARY',
		'ICELAND',
		'INDIA',
		'INDONESIA',
		'IRAN',
		'IRAQ',
		'IRELAND',
		'ISLE OF MAN',
		'ISRAEL',
		'ITALY',
		'JAMAICA',
		'JAPAN',
		'JERSEY',
		'JORDAN',
		'KAZAKHSTAN',
		'KENYA',
		'KIRIBATI',
		'KOSOVO',
		'KUWAIT',
		'KYRGYZSTAN',
		'LAOS PEOPLES DEMOCRATIC REPUBL',
		'LAOS',
		'LATVIA',
		'LEBANON',
		'LESOTHO',
		'LIBERIA',
		'LIBYAN ARAB JAMAHIRIYA',
		'LIECHTENSTEIN',
		'LITHUANIA',
		'LUXEMBOURG',
		'MACAU',
		'MACEDONIA',
		'MADAGASCAR',
		'MALAWI',
		'MALAYSIA',
		'MALDIVES',
		'MALI',
		'MALTA',
		'MARSHALL ISLANDS',
		'MARTINIQUE',
		'MAURITANIA',
		'MAURITIUS',
		'MAYOTTE',
		'MEXICO',
		'MICRONESIA, FEDERATED STATES O',
		'MOLDOVA',
		'MOLDOVA, REPUBLIC OF',
		'MONACO',
		'MONGOLIA',
		'MONTENEGRO',
		'MONTSERRAT',
		'MOROCCO',
		'MOZAMBIQUE',
		'MYANMAR',
		'NAMIBIA',
		'NAURU',
		'NEPAL',
		'NETH. ANTILLES',
		'NETHERLANDS ANTILLES',
		'NETHERLANDS',
		'NEW CALEDONIA',
		'NEW ZEALAND',
		'NICARAGUA',
		'NIGER',
		'NIGERIA',
		'NIUE',
		'NORFOLK ISLAND',
		'NORTH KOREA',
		'NORTHERN IRELAND',
		'NORTHERN MARIANA ISLANDS',
		'NORWAY',
		'OMAN',
		'PAKISTAN',
		'PALAU',
		'PALESTINIAN TERRITORY',
		'PANAMA',
		'PAPUA N. GUINEA',
		'PAPUA NEW GUINEA',
		'PARAGUAY',
		'PERU',
		'PHILIPPINES',
		'PITCAIRN',
		'POLAND',
		'PORTUGAL',
		'QATAR',
		'REPUBLIC OF GEORGIA',
		'REPUBLIC OF SINGAPORE',
		'REUNION',
		'RÉUNION',
		'ROMANIA',
		'RUSSIA',
		'RUSSIAN FEDERATION',
		'RWANDA',
		'SAINT BARTHELEMY',
		'SAINT HELENA',
		'SAINT KITTS AND NEVIS',
		'SAINT LUCIA',
		'SAINT MARTIN',
		'SAINT PIERRE AND MIQUELON',
		'SAINT VINCENT AND THE GRENADIN',
		'SAMOA (INDEPENDENT)',
		'SAN MARINO',
		'SAO TOME AND PRINCIPE',
		'SAUDI ARABIA',
		'SCOTLAND',
		'SENEGAL',
		'SERBIA AND MONTENEGRO',
		'SERBIA',
		'SEYCHELLES',
		'SIERRA LEONE',
		'SINGAPORE',
		'SINT MAARTEN (DUTCH PART)',
		'SLOVAK REPUBLIC',
		'SLOVAKIA',
		'SLOVENIA',
		'SOLOMON ISLANDS',
		'SOMALIA',
		'SOUTH AFRICA',
		'SOUTH GEORGIA AND THE SOUTH SA',
		'SOUTH GEORGIA',
		'SOUTH KOREA',
		'SPAIN',
		'SRI LANKA',
		'ST VINCENT',
		'SUDAN',
		'SURINAME',
		'SVALBARD AND JAN MAYEN ISLANDS',
		'SWAZILAND',
		'SWEDEN',
		'SWITZERLAND',
		'SYRIA',
		'SYRIAN ARAB REPUBLIC',
		'TAIWAN',
		'TAIWAN, PROVINCE OF CHINA',
		'TAJIKISTAN',
		'TANZANIA',
		'THAILAND',
		'THE NETHERLANDS',
		'TIMOR-LESTE',
		'TOGO',
		'TOKELAU',
		'TONGA',
		'TRINIDAD AND TOBAGO',
		'TRINIDAD',
		'TUNISIA',
		'TURKEY',
		'TURKMENISTAN',
		'TURKS AND CAICOS ISLANDS',
		'TUVALU',
		'UGANDA',
		'UK',
		'UKRAINE',
		'UNITED ARAB EMIRATES',
		'UNITED KINGDOM',
		'URUGUAY',
		'UZBEKISTAN',
		'VANUATU',
		'VENEZUELA',
		'VIETNAM',
		'VIRGIN ISLANDS (BRITISH)',
		'VIRGIN ISLANDS',
		'WALES',
		'WALLIS AND FUTUNA',
		'WEST INDIES',
		'WESTERN SAHARA',
		'YEMEN',
		'ZAMBIA',
		'ZIMBABWE',
	);
	return $countries;
}